#!/bin/sh
ssh ubuntu@3.143.231.231 <<EOF
    cd /home/apps/nodejs-vanillaJS-App 
    git pull https://github.com/iamibie/nodejs-vanillaJS-App.git master
    git config --global --add safe.directory /home/apps/nodejs-vanillaJS-App
    pm2 restart ecosystem.config.js
    exit
EOF