#!/bin/sh
   ssh root@3.143.231.231 <<EOF
    cd ~/home/apps/nodejs-vanillaJS-App/index.js
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    pm2 restart ecosystem.config.js
    exit
EOF